
#Sceen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Menu dimensions
MENU_WIDTH = 600
MENU_HEIGHT = 400

#Menu titles
MENU_TITLE = "Druksteroids Menu"
SELECTOR_TITLE = "Color game: "

#General properties
LINE_WIDTH = 2


#Player properties
PLAYER_RADIUS = 20 
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


#Asteroids propierties
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

#shooting properties
SHOT_RADIUS = 5
